spring.application.name=Weather
server.port=8081

spring.security.user.name=crysis
spring.security.user.password=Crysis@123

openweather.url=https://api.openweathermap.org/data/2.5/weather
openweather.apiKey={{apiKey}}